![descripcion](Logo_NBA.jpg)

In [1]:
#Importamos la librería Pandas y la librería Numpy
import pandas as pd
import numpy as np

In [9]:
#Importamos los dos dataset que hemos decidido utilizar para el análisis y los tenemos ya descargados y creamos los dataframes
df_avanzadas = pd.read_csv('nba_advanced_stats.csv')
df_est_sal = pd.read_csv('NBA_Player_Stats_and_Salaries_2010_2025.csv')

In [10]:
#Obtenemos la información general de cada dataframe
df_avanzadas.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Season  78 non-null     str
 1   Player  78 non-null     str
 2   Team    78 non-null     str
 3   Age     78 non-null     int64
 4   GP      78 non-null     int64
 5   MP      78 non-null     float64
 6   PER     78 non-null     float64
 7   TS%     78 non-null     float64
 8   USG%    78 non-null     float64
 9   WS      78 non-null     float64
 10  BPM     78 non-null     float64
 11  VORP    78 non-null     float64
dtypes: float64(7), int64(2), str(3)
memory usage: 7.4 KB

#Vemos que en las avanzadas hay 78 entradas y no encontramos nulos. 
#Tenemos tanto string, como int y floats

In [11]:
df_est_sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 7298 entries, 0 to 7297
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  7298 non-null   str
 1   Salary  7298 non-null   int64
 2   Year    7298 non-null   int64
 3   Pos     7298 non-null   str
 4   Age     7298 non-null   int64
 5   Team    7298 non-null   str
 6   G       7298 non-null   int64
 7   GS      7298 non-null   int64
 8   MP      7298 non-null   float64
 9   FG      7298 non-null   float64
 10  FGA     7298 non-null   float64
 11  FG%     7278 non-null   float64
 12  3P      7298 non-null   float64
 13  3PA     7298 non-null   float64
 14  3P%     6713 non-null   float64
 15  2P      7298 non-null   float64
 16  2PA     7298 non-null   float64
 17  2P%     7253 non-null   float64
 18  eFG%    7278 non-null   float64
 19  FT      7298 non-null   float64
 20  FTA     7298 non-null   float64
 21  FT%     7096 non-null   float64
 22  ORB     7298 non-null   float64
 23  DRB     7298 non-null   float64
 24  TRB     7298 non-null   float64
 25  AST     7298 non-null   float64
 26  STL     7298 non-null   float64
 27  BLK     7298 non-null   float64
 28  TOV     7298 non-null   float64
 29  PF      7298 non-null   float64
 30  PTS     7298 non-null   float64
dtypes: float64(23), int64(5), str(3)
memory usage: 1.7 MB

In [ ]:
#Esta es mucho más extensa y trataremos de recortarla para utilizar lo que realmente necesitamos
#Lo bueno es que tampoco tiene nulos, y también tiene strings, int y floats

In [ ]:
#Vamos a ver las primeras cinco filas de cada una. Son cinco filas y 31 columnas.
df_est_sal.head(5)

,Player,Salary,Year,Pos,Age,Team,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Kobe Bryant,23034375,2010,SG,31,LAL,73,73,38.8,9.8,...,0.811,1.1,4.3,5.4,5.0,1.5,0.3,3.2,2.6,27.0
1,Jermaine O'Neal,23016000,2010,C,31,MIA,70,70,28.4,5.6,...,0.720,1.8,5.2,6.9,1.3,0.4,1.4,1.8,3.0,13.6
2,Tracy McGrady,22843124,2010,SG,30,NYK,30,24,22.4,3.0,...,0.746,0.7,2.4,3.1,3.3,0.5,0.5,1.5,1.3,8.2
3,Tim Duncan,22183220,2010,C,33,SAS,78,77,31.3,7.2,...,0.725,2.8,7.3,10.1,3.2,0.6,1.5,1.8,1.9,17.9
4,Shaquille O'Neal,21000000,2010,C,37,CLE,53,53,23.4,4.9,...,0.496,1.8,4.9,6.7,1.5,0.3,1.2,2.0,3.2,12.0

In [ ]:
#Estas, al ser Estadísticas avanzadas, son mucho menos registros.
df_avanzadas.head(5)

,Season,Player,Team,Age,GP,MP,PER,TS%,USG%,WS,BPM,VORP
0,2023-24,Nikola Jokic,MIL,33,38,28.6,22.9,0.615,33.1,9.1,9.0,5.9
1,2023-24,Shai Gilgeous-alexander,NYK,32,30,27.5,13.8,0.583,31.7,10.7,3.3,5.9
2,2023-24,Giannis Antetokounmpo,POR,37,70,38.0,24.7,0.571,23.0,13.6,5.0,7.5
3,2023-24,Luka Doncic,CLE,29,73,29.2,20.0,0.652,31.6,7.4,4.1,6.1
4,2023-24,Joel Embiid,CHA,32,68,32.6,23.1,0.664,31.3,9.2,-0.4,1.7

In [16]:
#Reducimos el dataset para trabajar solo con los cinco últimos años y que no sea tan pesado
#Al nuevo dataset con los últimos cinco años, le vamos a llamar df_analisis, y es una copia del original para no tocar éste.
df_analisis = df_est_sal[df_est_sal['Year'] >= 2021].copy()

In [ ]:
#Comprobamos que está bien el cribado, y no hemos perdido columnas con información
df_analisis.info()
#Como vemos, hemos reducido los registros a 2474 entradas, pero mantenemos las 31 columnas originales.

<class 'pandas.DataFrame'>
RangeIndex: 2474 entries, 4824 to 7297
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  2474 non-null   str
 1   Salary  2474 non-null   int64
 2   Year    2474 non-null   int64
 3   Pos     2474 non-null   str
 4   Age     2474 non-null   int64
 5   Team    2474 non-null   str
 6   G       2474 non-null   int64
 7   GS      2474 non-null   int64
 8   MP      2474 non-null   float64
 9   FG      2474 non-null   float64
 10  FGA     2474 non-null   float64
 11  FG%     2463 non-null   float64
 12  3P      2474 non-null   float64
 13  3PA     2474 non-null   float64
 14  3P%     2397 non-null   float64
 15  2P      2474 non-null   float64
 16  2PA     2474 non-null   float64
 17  2P%     2450 non-null   float64
 18  eFG%    2463 non-null   float64
 19  FT      2474 non-null   float64
 20  FTA     2474 non-null   float64
 21  FT%     2395 non-null   float64
 22  ORB     2474 non-null   float64
 23  DRB     2474 non-null   float64
 24  TRB     2474 non-null   float64
 25  AST     2474 non-null   float64
 26  STL     2474 non-null   float64
 27  BLK     2474 non-null   float64
 28  TOV     2474 non-null   float64
 29  PF      2474 non-null   float64
 30  PTS     2474 non-null   float64
dtypes: float64(23), int64(5), str(3)
memory usage: 599.3 KB

In [18]:
#Vamos a ver los cinco mejores reboteadores por año, agrupando por año y en orden de más a menos rebotes
top_reboteadores = df_analisis.sort_values(['Year', 'TRB'], ascending=[True, False]).groupby('Year').head(5)
#Ahora voy a mostrar solo el nombre del jugador, el año y el total de rebotes de cada uno
top_reboteadores[['Year', 'Player', 'TRB']]

      Year                 Player   TRB
4881  2021           Clint Capela  14.3
4860  2021            Rudy Gobert  13.5
4897  2021      Jonas Valanciunas  12.5
4854  2021         Andre Drummond  12.0
4874  2021       Domantas Sabonis  12.0
5322  2022            Rudy Gobert  14.7
5335  2022           Nikola Jokic  13.8
5366  2022       Domantas Sabonis  12.1
5793  2022           Jaylen Hoard  12.0
5373  2022           Clint Capela  11.9
5863  2023          Anthony Davis  12.5
5905  2023       Domantas Sabonis  12.3
5857  2023  Giannis Antetokounmpo  11.8
5861  2023            Rudy Gobert  11.6
5918  2023           Steven Adams  11.5
6357  2024       Domantas Sabonis  13.7
6327  2024            Rudy Gobert  12.9
6329  2024          Anthony Davis  12.6
6542  2024            Jalen Duren  11.6
6323  2024  Giannis Antetokounmpo  11.5
6834  2025       Domantas Sabonis  13.9
6816  2025     Karl-Anthony Towns  12.8
6811  2025           Nikola Jokic  12.7
6948  2025            Ivica Zubac  12.6
7105  2025         Walker Kessler  12.2

In [ ]:
#Vamos a mostrar las estadísticas avanzadas:
#PER: El PER (Player Efficiency Rating) es, en esencia, una medida de la productividad por minuto de un jugador.


#¿Cómo se calcula (a grandes rasgos)?
#No es necesaria la fórmula matemática, solo entender qué suma y qué resta:

#Suman: Puntos, rebotes, asistencias, robos, tapones y tiros anotados.

#Restan: Tiros fallados (de campo y libres), pérdidas de balón y faltas personales.

#las 3 claves para entenderlo:
#El "Minuto a Minuto": El PER no premia a alguien solo por jugar mucho tiempo. Si un suplente juega 10 minutos y produce muchísimo, tendrá un PER más alto que un titular que juega 35 minutos pero no hace nada relevante.

#El Promedio es 15: 

#Si tienes un PER de 20, es prácticamente de una estrella.

#Si tienes un PER de 30 o más, estás teniendo una temporada histórica (nivel MVP).

#Ajuste de Equipo: La fórmula tiene un ajuste para que los jugadores de equipos que juegan muy rápido (donde hay más oportunidades de sumar estadísticas) no tengan una ventaja injusta sobre los que juegan en equipos más lentos.

#¿Cuál es su punto débil?
#El PER es muy bueno midiendo la ofensiva, pero se queda corto con la defensa.

#Como la hoja de estadísticas básica solo registra robos y tapones, el PER no puede medir si un jugador defiende bien la posición, si molesta los tiros del rival o si hace una rotación perfecta. Por eso, algunos especialistas defensivos tienen un PER bajo, aunque sean vitales para ganar.

In [1]:

df = pd.read_csv('nba_advanced_stats.csv')

# 1. Renombrar columnas para que tengan sentido técnico
columnas_nuevas = {
    'Estación': 'Season',
    'Jugador': 'Player',
    'Equipo': 'Team',
    'Edad': 'Age',
    'Médico de cabecera': 'MP',
    'diputado': 'TS%',
    'PORTS%': 'PER',
    'Gestión de procesos de negocio (BPM)': 'BPM'
}
df.rename(columns=columnas_nuevas, inplace=True)

# 2. Limpiar decimales (cambiar ',' por '.' y convertir a numérico)
cols_numericas = ['TS%', 'USG%', 'PER', 'BPM', 'VORP', 'WS']
for col in cols_numericas:
    if df[col].dtype == 'object':
        df[col] = df[col].str.replace(',', '.').astype(float)

print("Datos listos para el Proyecto_NBA")
print(df.head())

NameError: name 'pd' is not defined