# PRESENTACION DEL ANALISIS DE DATOS BASADO EN ESTADISTICA PARA JUGADORES DE  LA NBA 
---
![descripcion](Imagen_NBA.png)

# DATA
>Partimos de Databases obtenidas de la página oficial de la NBA Estadísticas, directamente o tratados.
El primer CSV incluye datos habituales entre 2010 y 2025, lo reduciré a lo que me interesa, pero es la más adecuada que he encontrado.
El segundo CSV incluye datos de estadística avanzada y el campo Player es común en las dos, por lo que intentaré jugar con ellas de esta forma.

In [14]:
import pandas as pd
path="Datos/nba_advanced_stats.csv"
est_avanzadas = pd.read_csv(path)

In [15]:
est_avanzadas.head()

,Season,Player,Team,Age,GP,MP,PER,TS%,USG%,WS,BPM,VORP
0,2023-24,Nikola Jokic,MIL,33,38,28.6,22.9,0.615,33.1,9.1,9.0,5.9
1,2023-24,Shai Gilgeous-alexander,NYK,32,30,27.5,13.8,0.583,31.7,10.7,3.3,5.9
2,2023-24,Giannis Antetokounmpo,POR,37,70,38.0,24.7,0.571,23.0,13.6,5.0,7.5
3,2023-24,Luka Doncic,CLE,29,73,29.2,20.0,0.652,31.6,7.4,4.1,6.1
4,2023-24,Joel Embiid,CHA,32,68,32.6,23.1,0.664,31.3,9.2,-0.4,1.7

In [16]:

est_salarios = pd.read_csv("Datos/NBA_Player_Stats_and_Salaries_2010_2025.csv")
est_salarios.head()

,Player,Salary,Year,Pos,Age,Team,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Kobe Bryant,23034375,2010,SG,31,LAL,73,73,38.8,9.8,...,0.811,1.1,4.3,5.4,5.0,1.5,0.3,3.2,2.6,27.0
1,Jermaine O'Neal,23016000,2010,C,31,MIA,70,70,28.4,5.6,...,0.720,1.8,5.2,6.9,1.3,0.4,1.4,1.8,3.0,13.6
2,Tracy McGrady,22843124,2010,SG,30,NYK,30,24,22.4,3.0,...,0.746,0.7,2.4,3.1,3.3,0.5,0.5,1.5,1.3,8.2
3,Tim Duncan,22183220,2010,C,33,SAS,78,77,31.3,7.2,...,0.725,2.8,7.3,10.1,3.2,0.6,1.5,1.8,1.9,17.9
4,Shaquille O'Neal,21000000,2010,C,37,CLE,53,53,23.4,4.9,...,0.496,1.8,4.9,6.7,1.5,0.3,1.2,2.0,3.2,12.0

# CONCEPTOS BASICOS
>Conceptos habituales y conocidos del baloncesto como puntos, rebotes, asistencias, etc.
Conceptos habituales y conocidos de cualquier persona como nombre del jugador, edad, altura, etc.
Conceptos menos habituales de estadística avanzada como PER, USG%, WS o BPM. En principio nos fijaremos en el PER, que es el nivel de eficiencia general de cada jugador. Si no obtengo resultados, buscaré y explicaré otra.

# OBJETIVO E HIPOTESIS
>El objetivo es poner de manifiesto la importancia de las estadística normales a la hora de fichar un jugador, pero también cómo las avanzadas pueden ayudar mucho a tomar la decisión (no se utiliza mucho aún en España.)

Las hipótesis que quiero analizar en base a estos datos, van dirigidas a cuanto me puede servir la estadistica normal y la avanzada a la hora de valorar a un jugador, y son las siguientes, sin perjuicio de añadir alguna otra posteriormente:
- Los jugadores con más puntos anotados están entre los que maás cobran
- Los jugadores con más rebotes están en los mejores quintetos de cada año
- Hay jugadores con un PER elevado y que sin embargo no está entre los que más cobran.